services:
  # static-site:
  #   image: dockersamples/static-site
  #   build: .
  #   ports:
  #     - "80:80"
  #   restart: always
    
  ngrok:
    image: ngrok/ngrok:latest
    command:
      - "http"
      # - "http://host.docker.internal:80"
      - "--url=pleasant-stunning-owl.ngrok-free.app"
      - "webhook:5000"
    environment:
      NGROK_AUTHTOKEN: 2q18JJ95wEMhumPXheVhnKnpcu5_2MTCju2dwr1ZJM5GUPzvF
    ports:
      - 4040:4040
    restart: always

  youtube-noti-before_live:
    build:
      context: .          
      dockerfile: Dockerfile  
    container_name: noti-before_live-container
    env_file:
      - .env              
    volumes:
      - ./assets:/youtube_noti/assets  
      - ./:/youtube_noti
    restart: always     
    command: python botSendMessage.py
    environment:
      - PYTHONUNBUFFERED=1

  bot-discord:
    build:
      context: .          
      dockerfile: Dockerfile  
    container_name: bot-discord-container
    env_file:
      - .env              
    volumes:
      - ./assets:/youtube_noti/assets  
      - ./:/youtube_noti 
    restart: always     
    command: python botDiscord.py

  webhook:
    build:
      context: .          
      dockerfile: Dockerfile  
    container_name: webhookcontainer
    env_file:
      - .env              
    volumes:
      - ./assets:/youtube_noti/assets  
      - ./:/youtube_noti
    restart: always    
    ports:
      - "5000:5000"   # เพิ่มบรรทัดนี้ 
    command: python receive_webhook.py
    environment:
      - PYTHONUNBUFFERED=1

  subscribe-channel:
    build:
      context: .          
      dockerfile: Dockerfile  
    container_name: subscribe-channel-container
    env_file:
      - .env              
    volumes:
      - ./assets:/youtube_noti/assets  
      - ./:/youtube_noti
    restart: always    
    command: python subscribe_to_channel.py
    environment:
      - PYTHONUNBUFFERED=1
